Makefile, README.md, src/chaotic.sh, src/lib/base-make.sh, src/lib/interfere.sh, src/lib/keyring.sh
It is worthless as currently implemented, because sources from any package could be signed using keys from sources of any other package. In the future, we will implement this in a per-package basis.
=> Disable source GnuPG checking

guest/Singularity, guest/bin/internal-makepkg, guest/etc/makepkg.conf, src/chaotic.sh, src/lib/base-make.sh, src/lib/cleanup.sh, src/lib/deploy.sh, src/lib/package-make.sh, src/lib/utils.sh
* Move PKGDEST from `"~/pkgdest"` to `"/var/pkgdest"` -- This way it won't be caught in the home's `chown -R`.
* Change default CAUR_OVERLAY_TYPE to `kernel`;
* Readd `set -euo pipefail` that was miss-removed;
* Do linter complains.
=> Move pkgdest to /var/pkgdest

services/chaotic-afternoon.service, services/chaotic-hourly.service, services/chaotic-midnight.service, services/chaotic-morning.service, services/chaotic-nightly.service, services/chaotic-tkg-kernels.service, services/chaotic-tkg-wine.service, src/lib/base-make.sh, src/lib/deploy.sh, src/lib/package-makedir.sh, src/lib/routines-tkg-wine.sh, src/lib/routines-tkg.sh, src/lib/routines.sh
* Parallel upload of files/packages (instead of splitting a single file into smaller parts);
* Ensure sending signatures after packages;
* Get the building sequence from the routines' lists;
* Count build threads properly;
* External (systemd's unit) frozen notifier;
* Say remaining packages count in the frozen notification.
New time limits (systemd only):
* hourly: 4hrs
* morning/afternoon/nightly: 6hrs
* tkg-kernels: 24hrs
* tkg-wine: 6hrs
=> Refactor parallelization

src/lib/deploy.sh
I wanted to deploy a package and saw this. Unacceptable.
Yes yes I know, stereotypical pull request, but this makes chaotic completely unusable let's be honest.
=> Fix typo in src/lib/deploy.sh

src/lib/routines-tkg.sh
In a few cases, ThinLTO even outperforms full LTO, most likely because the higher scalability of ThinLTO allows using a more aggressive backend optimization pipeline (similar to that of a non-LTO build). - [LLVM Blog](https://blog.llvm.org/2016/06/thinlto-scalable-and-incremental-lto.html)
Thin LTO supports much better parallelism than fat LTO. It can achieve similar performance improvements as fat LTO (sometimes even better) while taking much less total time by taking advantage of more CPUs. - [Rust Lang blog](https://blog.rust-lang.org/inside-rust/2020/06/29/lto-improvements.html).
My understanding is that normally Full LTO disables some optimizations that don't scale with the increased size of the optimization unit, but because Thin LTO deals with smaller optimization units, it can …
=> Switch to thin lto for LTO builds.

guest/etc/pacman.conf
It will speed up the downloading process.
=> Enable parallel downloads by default.

README.md, src/chaotic.sh, src/lib/interfere.sh, src/lib/routines-tkg-wine.sh, src/lib/routines-tkg.sh, src/lib/routines.sh, src/lib/sync.sh
New procedure for rebuilding packages:
chaotic get package1 package2 package3
chaotic bump package1 package2 package3
chaotic mkd
No more chaotic rm! Yay!
=> Bump pkgrel via decimal bumps instead, support epoch, add chaotic {interfere-bump,bump}

src/lib/aur.sh, src/lib/routines.sh
Chaotic get will now check the package lists to check if there is another source available for the package other than the aur. Sometimes we use external git sources directly instead of the aur, and this makes us download the correct package.
=> Improve chaotic get

services/chaotic-afternoon.service, services/chaotic-hourly.service, services/chaotic-midnight.service, services/chaotic-morning.service, services/chaotic-nightly.service, services/chaotic-sort-logs.service, services/chaotic-tkg-kernels.service, services/chaotic-tkg-wine.service
It makes sense to add `network-online.target` as a dependency of the services since that they **requires** the network to be up. It helps a lot to solve problems like the following on machines that are constantly rebooted/hibernated like desktop computers/laptops:
_Logs are in reverse order_
```
Apr 25 23:08:02 CatBuilder systemd[1]: chaotic-tkg-kernels.service: Failed with result 'exit-code'.
Apr 25 23:08:02 CatBuilder systemd[1]: chaotic-tkg-kernels.service: Main process exited, code=exited, status=128/n/a
Apr 25 23:08:02 CatBuilder chaotic[58]: fatal: unable to access 'https://github.com/Frogging-Family/linux-tkg.git/': Could not resolve host: github.com
Apr 25 23:08:02 CatBuilder chaotic[56]: Cloning into 'linux-tkg'...
Apr 25 23:08:02 CatBuilder chaotic[55]: rm: cannot remove …
```
=> Add network-online.target dependency to services.

src/lib/routines-tkg.sh
Needed to not build 5.17 kernel variations anymore and fix https://github.com/chaotic-aur/packages/issues/1458.
=> Linux-tkg 5.18 kernel builds shall start!

src/chaotic.sh, src/lib/base-make.sh
There are cases where the mirror from cloudflaremirrors fail, for example I'm getting a 500 response from cloudflaremirrors since some weeks ago and therefore the packages fail to build. The errors that I'm getting are (in reverse order):
```
Jun 22 21:07:25 CatBuilder systemd-machined[407]: Machine pkgfae4d382cef terminated.
Jun 22 21:07:25 CatBuilder systemd[1]: machine-pkgfae4d382cef.scope: Deactivated successfully.
Jun 22 21:07:25 CatBuilder chaotic[1003064]: [58B blob data]
Jun 22 21:07:25 CatBuilder chaotic[1003064]: error: failed to prepare transaction (could not find database)
Jun 22 21:07:25 CatBuilder chaotic[1003064]: warning: xz-5.2.5-3 is up to date -- skipping
Jun 22 21:07:25 CatBuilder chaotic[1003064]: warning: tar-1.34-1 is up to date -- skipping
Jun 22 21:07:25 …
```
=> Add an additional mirror in case that the first one fails.

README.md, src/chaotic.sh, src/lib/database.sh, src/lib/utils.sh
Completely rebuild the database and files database from scratch, keeping the original DB around until the build is finished. This allows us to easily fix broken db entries without causing any downtime to chaotic.
This re-uses logic already used in db-bump.
=> Add db-rebuild subcommand to rebuild the database from scratch

src/lib/routines-tkg.sh
This reverts commit e240e4835499f77f963b68e54050ec069d0211c1. The issue has been fixed in https://github.com/koverstreet/bcachefs/issues/447#issuecomment-1214449165.
=> Revert "Temporarily disable bcachefs"

src/lib/routines-tkg.sh
This reverts commit a4c2deb016bfd73f9efb29fdf072562949d4f4f6. We are
disabling bcachefs on our main builds from now, bcachefs will be moved to
new kernel variants with -bcachefs in its name to avoid the patch
breaking the main kernels every time.
=> Revert "Revert "Temporarily disable bcachefs" (#56)"

guest/Singularity
Signed-off-by: Gontier Julien <gontierjulien68@gmail.com>
As discussed here #59 we are going now to directly grab the base-devel image from archlinux.
(it also save a bit of time and is more efficient :D)
=> Change to the base docker image to the base-devel one

src/lib/package-make.sh, src/lib/package-prepare.sh
1. Ensure the hosts file is respected inside the systemd-nspawn container
2. hardcode path of bash in the wizard (env is not yet initialized)
=> Some nixos compatiblity changes

src/chaotic.c
Variable goes out of scope, which causes undefined behaviour
=> Fix undefined behaviour in chaotic.c

src/lib/interfere.sh
As seen in https://github.com/chaotic-aur/packages/issues/2038, groups are still not being removed from PKGBUILDs successfully.
=> Fix groups not getting removed

src/lib/package-makedir.sh
Basically, the idea is to get us rid of having to clear source caches by hand by checking the log of the failed build for known patterns indicating cache cleaning.
=> Add basic resilience against failed builds

install-hpc-cluster.sh, src/lib/pkgrel-incrementer.sh, src/lib/routines.sh
Only for the Singularity engine (for now?)
I know, this is utterly hackish. Changes already in production on the Slurm cluster.
=> Start pkgrel_increment service in background during routines

src/lib/routines-tkg.sh
Since 5.15 LTS variations miserably fail building and the newest LTS release is 6.1, they need to get bumped.
=> Bump LTS linux-tkg to 6.1

src/lib/routines-tkg.sh
Currently, input is required to activate it. This fixes this behavior. Also sort _LINUX_SCHED array alphabetically.
=> feat(routines-tkg): replace anbox with waydroid

src/lib/interfere.sh
Use alternate method to get rid of PKGEXT, groups, replaces.  `sed` fails to catch many cases.  Use `unset` instead.
Add missing newline at end of PKGBUILD.  Packages that are missing a newline at the end of the file abort without doing anything.
<details><summary>nuclear-player-bin.log</summary>
```
Building package "nuclear-player-bin"
:: Synchronizing package databases...
core downloading...
extra downloading...
community downloading...
multilib downloading...
chaotic-aur downloading...
:: Starting full system upgrade...
there is nothing to do
umount: /home/xiota/nuclear-player-bin/machine/root/home/main-builder/pkgwork unmounted
umount: /home/xiota/nuclear-player-bin/machine/root/home/main-builder/.ccache unmounted
umount: /home/xiota/nuclear-player-bin/machine/root/home/main-builder/p …
```
=> Use alternate method to get rid of PKGEXT, groups, replaces

src/lib/interfere.sh
#93 causes following message because of `unset PKGEXT`. This replaces it with `PKGEXT='.pkg.tar.zst'`.
```
==> WARNING: '' is not a valid archive extension.
```
@dr460nf1r3 @PedroHLC
=> Fix PKGEXT

src/lib/interfere.sh
An idea to make tracking interfered packages easier.  Add an optdep on `chaotic-interfere` to interfered packages.  Shouldn't affect building, and the following command would show a list of interfered packages in the repository (would need to create a dummy package):
```
pactree -usr -o1 -d1 chaotic-interfere
```
Not using:
* `depends` - interferes with build / install.  However, would make visible in logs that an interfere was used.
* `makedepends` - interferes with build / install, and not visible afterwards.  Would be visible in logs.  Maybe use in combination with optdep?
* `pkgdesc` - difficult to cover all cases.
* Something else - I probably don't know it exists.
=> Add optdep to track interfered packages

Makefile, src/lib/routines-garuda.sh, src/lib/routines.sh
I'm planning to consolidate all PKGBUILD repos Garuda currently has into [one repo](https://gitlab.com/garuda-linux/pkgbuilds) to simplify maintenance and make finding individual PKGBUILDs easier for potential contributors. 
Since the toolbox currently does not support PKGBUILDs not residing in a single repo, a workaround had to be implemented.
=> feat: add Garuda routine

slurm-jobs/ufscar-hpc/daily.1.sh, slurm-jobs/ufscar-hpc/hourly.1.sh, slurm-jobs/ufscar-hpc/hourly.2.sh
The old code worked nice when all the computer-nodes were the same, but since we added the 2x32x2 EPICs we weren't using all the available cores, and some apps were even wrongly detecting the topology overloading the pinned cores.
=> hpc: use all cores+mem available
